### ISSUE TITLE
Use WP-CLI

### ISSUE THREAD

**Issue by joellobo1234** [vipullinux/rtcampAssignment#10]
Using WP-CLI can cut down your efforts.

Please move all WordPress related part to https://wp-cli.org/

When you are done close this issue via Github commit.

**Comment by bipulkumar7** [comment]
Just try on 16.04 LTS  16.04 Codename: xenial  Desktop. Hope it works !
[To run: sudo ./RTCAMP](https://github.com/vipullinux/rtcampAssignment/blob/master/RTCAMP)
