### ISSUE TITLE
Improper message to open site

### ISSUE THREAD

**Issue by gau1991** [vipullinux/rtcampAssignment#4]
Hi,

```
Nginx is successfull installed
Kindly open your browser http://localhost/example.com 
```

As I was going to open http://localhost/example.com on my browser, it was showing error,
I think site name must be http://example.com not with localhost

**Comment by bipulkumar7** [comment]
Could you be more specific, what error are you getting? While opening localhost/example_com, I mean it might help me a lot , if you pastebin me your error messages.

**Comment by gau1991** [comment]
@vipullinux ,
My Bad, it is not throwing error..
I got bit confused, as I entered site name as `example.com`, but script told to open `http://localhost/example.com`.
I am still confused
I think, as I have to create site `example.com`, script must create `http://example.com` not  `http://localhost/example.com`

**Comment by gau1991** [comment]
I think its related with #6
